! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module formatrix
 use, intrinsic :: ISO_C_BINDING
 implicit none

 ! PUBLIC METHODS AND TYPES
 public :: Matrix
 ! TYPES
 type :: Matrix
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
  logical, public :: swigown = .false.
 contains
  procedure :: create => swigf_new_Matrix
  procedure :: num_rows => swigf_Matrix_num_rows
  procedure :: num_nnz => swigf_Matrix_num_nnz
  procedure :: row_nnz => swigf_Matrix_row_nnz
  procedure :: get_column => swigf_Matrix_get_column
  procedure :: get_value => swigf_Matrix_get_value
  procedure :: get_columns => swigf_Matrix_get_columns
  procedure, private :: get_values__SWIG_0 => swigf_Matrix_get_values__SWIG_0
  procedure :: get_row_ptrs => swigf_Matrix_get_row_ptrs
  procedure :: get_col_inds => swigf_Matrix_get_col_inds
  procedure, private :: get_values__SWIG_1 => swigf_Matrix_get_values__SWIG_1
  procedure :: release => swigf_delete_Matrix
  generic :: get_values => get_values__SWIG_0, get_values__SWIG_1
 end type

 ! WRAPPER DECLARATIONS
 private
 interface
  function swigc_new_Matrix(farg1, farg2) &
     bind(C, name="swigc_new_Matrix") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   integer(C_INT), intent(in) :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_Matrix_num_rows(farg1) &
     bind(C, name="swigc_Matrix_num_rows") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_Matrix_num_nnz(farg1) &
     bind(C, name="swigc_Matrix_num_nnz") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_Matrix_row_nnz(farg1, farg2) &
     bind(C, name="swigc_Matrix_row_nnz") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_Matrix_get_column(farg1, farg2, farg3) &
     bind(C, name="swigc_Matrix_get_column") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
   integer(C_INT), intent(in) :: farg3
  end function
  function swigc_Matrix_get_value(farg1, farg2, farg3) &
     bind(C, name="swigc_Matrix_get_value") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
   integer(C_INT), intent(in) :: farg3
  end function
  function swigc_Matrix_get_columns(farg1, farg2) &
     bind(C, name="swigc_Matrix_get_columns") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_Matrix_get_values__SWIG_0(farg1, farg2) &
     bind(C, name="swigc_Matrix_get_values__SWIG_0") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
   integer(C_INT), intent(in) :: farg2
  end function
  function swigc_Matrix_get_row_ptrs(farg1) &
     bind(C, name="swigc_Matrix_get_row_ptrs") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_Matrix_get_col_inds(farg1) &
     bind(C, name="swigc_Matrix_get_col_inds") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_Matrix_get_values__SWIG_1(farg1) &
     bind(C, name="swigc_Matrix_get_values__SWIG_1") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
   type(C_PTR), value :: farg1
  end function
  subroutine swigc_delete_Matrix(farg1) &
     bind(C, name="swigc_delete_Matrix")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
 end interface

contains
  ! FORTRAN PROXY CODE
  subroutine swigf_new_Matrix(self, nx, ny)
   use, intrinsic :: ISO_C_BINDING
   class(Matrix) :: self
   integer(C_INT), intent(in) :: nx
   integer(C_INT), intent(in) :: ny
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_Matrix(nx, ny)
   self%swigown = .true.
  end subroutine
  function swigf_Matrix_num_rows(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(Matrix) :: self
   fresult = swigc_Matrix_num_rows(self%swigptr)
  end function
  function swigf_Matrix_num_nnz(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(Matrix) :: self
   fresult = swigc_Matrix_num_nnz(self%swigptr)
  end function
  function swigf_Matrix_row_nnz(self, row) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(Matrix) :: self
   integer(C_INT), intent(in) :: row
   fresult = swigc_Matrix_row_nnz(self%swigptr, row)
  end function
  function swigf_Matrix_get_column(self, row, col_offset) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT) :: fresult
   class(Matrix) :: self
   integer(C_INT), intent(in) :: row
   integer(C_INT), intent(in) :: col_offset
   fresult = swigc_Matrix_get_column(self%swigptr, row, col_offset)
  end function
  function swigf_Matrix_get_value(self, row, col_offset) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE) :: fresult
   class(Matrix) :: self
   integer(C_INT), intent(in) :: row
   integer(C_INT), intent(in) :: col_offset
   fresult = swigc_Matrix_get_value(self%swigptr, row, col_offset)
  end function
  function swigf_Matrix_get_columns(self, row) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT), pointer :: fresult(:)
   class(Matrix) :: self
   integer(C_INT), intent(in) :: row
   call c_f_pointer(swigc_Matrix_get_columns(self%swigptr, row), fresult, [swigf_Matrix_row_nnz(self,row)])
  end function
  function swigf_Matrix_get_values__SWIG_0(self, row) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE), pointer :: fresult(:)
   class(Matrix) :: self
   integer(C_INT), intent(in) :: row
   call c_f_pointer(swigc_Matrix_get_values__SWIG_0(self%swigptr, row), fresult, [swigf_Matrix_row_nnz(self,row)])
  end function
  function swigf_Matrix_get_row_ptrs(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT), pointer :: fresult(:)
   class(Matrix) :: self
   call c_f_pointer(swigc_Matrix_get_row_ptrs(self%swigptr), fresult, [swigf_Matrix_num_rows(self)])
  end function
  function swigf_Matrix_get_col_inds(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   integer(C_INT), pointer :: fresult(:)
   class(Matrix) :: self
   call c_f_pointer(swigc_Matrix_get_col_inds(self%swigptr), fresult, [swigf_Matrix_num_nnz(self)])
  end function
  function swigf_Matrix_get_values__SWIG_1(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE), pointer :: fresult(:)
   class(Matrix) :: self
   call c_f_pointer(swigc_Matrix_get_values__SWIG_1(self%swigptr), fresult, [swigf_Matrix_num_nnz(self)])
  end function
  subroutine swigf_delete_Matrix(self)
   use, intrinsic :: ISO_C_BINDING
   class(Matrix) :: self
   if (self%swigown) then
    call swigc_delete_Matrix(self%swigptr)
    self%swigown = .false.
   end if
   self%swigptr = C_NULL_PTR
  end subroutine
end module formatrix
