! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module timer
 use, intrinsic :: ISO_C_BINDING
 implicit none

 ! PUBLIC METHODS AND TYPES
 public :: timer
 ! TYPES
 type :: timer
  ! These should be treated as PROTECTED data
  type(C_PTR), public :: swigptr = C_NULL_PTR
  logical, public :: swigown = .false.
 contains
  procedure :: create => swigf_new_timer
  procedure :: start => swigf_timer_start
  procedure :: stop => swigf_timer_stop
  procedure :: reset => swigf_timer_reset
  procedure :: walltime => swigf_timer_walltime
  procedure :: cputime => swigf_timer_cputime
  procedure :: release => swigf_delete_timer
 end type

 ! WRAPPER DECLARATIONS
 private
 interface
  function swigc_new_timer() &
     bind(C, name="swigc_new_timer") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR) :: fresult
  end function
  subroutine swigc_timer_start(farg1) &
     bind(C, name="swigc_timer_start")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
  subroutine swigc_timer_stop(farg1) &
     bind(C, name="swigc_timer_stop")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
  subroutine swigc_timer_reset(farg1) &
     bind(C, name="swigc_timer_reset")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
  function swigc_timer_walltime(farg1) &
     bind(C, name="swigc_timer_walltime") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE) :: fresult
   type(C_PTR), value :: farg1
  end function
  function swigc_timer_cputime(farg1) &
     bind(C, name="swigc_timer_cputime") &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE) :: fresult
   type(C_PTR), value :: farg1
  end function
  subroutine swigc_delete_timer(farg1) &
     bind(C, name="swigc_delete_timer")
   use, intrinsic :: ISO_C_BINDING
   type(C_PTR), value :: farg1
  end subroutine
 end interface

contains
  ! FORTRAN PROXY CODE
  subroutine swigf_new_timer(self)
   use, intrinsic :: ISO_C_BINDING
   class(timer) :: self
   if (c_associated(self%swigptr)) call self%release()
   self%swigptr = swigc_new_timer()
   self%swigown = .true.
  end subroutine
  subroutine swigf_timer_start(self)
   use, intrinsic :: ISO_C_BINDING
   class(timer) :: self
   call swigc_timer_start(self%swigptr)
  end subroutine
  subroutine swigf_timer_stop(self)
   use, intrinsic :: ISO_C_BINDING
   class(timer) :: self
   call swigc_timer_stop(self%swigptr)
  end subroutine
  subroutine swigf_timer_reset(self)
   use, intrinsic :: ISO_C_BINDING
   class(timer) :: self
   call swigc_timer_reset(self%swigptr)
  end subroutine
  function swigf_timer_walltime(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE) :: fresult
   class(timer) :: self
   fresult = swigc_timer_walltime(self%swigptr)
  end function
  function swigf_timer_cputime(self) &
     result(fresult)
   use, intrinsic :: ISO_C_BINDING
   real(C_DOUBLE) :: fresult
   class(timer) :: self
   fresult = swigc_timer_cputime(self%swigptr)
  end function
  subroutine swigf_delete_timer(self)
   use, intrinsic :: ISO_C_BINDING
   class(timer) :: self
   if (self%swigown) then
    call swigc_delete_timer(self%swigptr)
    self%swigown = .false.
   end if
   self%swigptr = C_NULL_PTR
  end subroutine
end module timer
